### ISSUE TITLE
Not Mirroring Unusual DeviantArt Link

### ISSUE THREAD

**Issue by kupiakos** [kupiakos/LapisMirror#37]
[DeviantArt Link](http://ravalinne.deviantart.com/art/Platonic-hand-holding-634164728?ga_submit_new=10%253A1473726401)

[Reddit Comment](https://www.reddit.com/r/Undertale/comments/52ho4z/platonic_hand_holding/d7kbo8b)

**Comment by spiral6** [comment]
Yeah, something's odd with this picture. I don't know why RES can't open it. 

For reference, I used the same URL here. https://www.reddit.com/r/bottest/comments/5kr3qi/a_test_for_mirroring_images_for_my_bot/

I assume, by removing this part at the end of the url, "?ga_submit_new=10%253A1473726401", it should work.

**Comment by Shugabuga** [comment]
Here are the relevant logs:

    2016-12-28T16:52:07.985470+00:00 app[lapisshuga01.1]: DEBUG - Processing submission
    2016-12-28T16:52:07.985483+00:00 app[lapisshuga01.1]:         permalink:https://www.reddit.com/r/heyitsshugatest/comments/5kr6jh/another_issue_40_thing/
    2016-12-28T16:52:07.985484+00:00 app[lapisshuga01.1]:         url:      http://ravalinne.deviantart.com/art/Platonic-hand-holding-634164728
    2016-12-28T16:52:09.314142+00:00 app[lapisshuga01.1]: DEBUG - Calling import_submission() on plugins
    2016-12-28T16:52:09.314619+00:00 app[lapisshuga01.1]: DEBUG - Querying DA API http://backend.deviantart.com/oembed?format=json&url=http%3A%2F%2Fravalinne.deviantart.com%2Fart%2FPlatonic-hand-holding-634164728
    2016-12-28T16:52:09.314467+00:00 app[lapisshuga01.1]: DEBUG - http://ravalinne.deviantart.com/art/Platonic-hand-holding-634164728 is valid DA url.
    2016-12-28T16:52:09.534063+00:00 app[lapisshuga01.1]: DEBUG - Author name: Ravalinne
    2016-12-28T16:52:09.534201+00:00 app[lapisshuga01.1]: DEBUG - Found DA API url ['http://img01.deviantart.net/9a74/i/2016/256/c/d/platonic_hand_holding_by_ravalinne-dahkcmw.png']
    2016-12-28T16:52:10.493159+00:00 app[lapisshuga01.1]: DEBUG - Found full DA image url: http://img01.deviantart.net/9a74/i/2016/256/c/d/platonic_hand_holding_by_ravalinne-dahkcmw.png
    2016-12-28T16:52:10.493405+00:00 app[lapisshuga01.1]: INFO  - Successfully imported data from DeviantArtPlugin.import_submission()
    2016-12-28T16:52:10.493831+00:00 app[lapisshuga01.1]: 
    2016-12-28T16:52:10.493830+00:00 app[lapisshuga01.1]: INFO  - 
    2016-12-28T16:52:10.493835+00:00 app[lapisshuga01.1]: Imported data from submission "http://ravalinne.deviantart.com/art/Platonic-hand-holding-634164728"
    2016-12-28T16:52:10.494071+00:00 app[lapisshuga01.1]: DEBUG - Import info: [{'importer_display': {'header': 'Mirrored deviantArt image by the author "Ravalinne":\n\n'}, 'author': 'Ravalinne', 'import_urls': ['http://img01.deviantart.net/9a74/i/2016/256/c/d/platonic_hand_holding_by_ravalinne-dahkcmw.png'], 'source': 'http://ravalinne.deviantart.com/art/Platonic-hand-holding-634164728'}]
    2016-12-28T16:52:10.494287+00:00 app[lapisshuga01.1]: DEBUG - Calling export_submission() on plugins
    2016-12-28T16:52:10.494527+00:00 app[lapisshuga01.1]: DEBUG - A single image will be uploaded.
    2016-12-28T16:52:10.494736+00:00 app[lapisshuga01.1]: DEBUG - Uploading URL "http://img01.deviantart.net/9a74/i/2016/256/c/d/platonic_hand_holding_by_ravalinne-dahkcmw.png" to imgur
    2016-12-28T16:52:11.020522+00:00 app[lapisshuga01.1]: ERROR - Broken exception catch Traceback (most recent call last):
    2016-12-28T16:52:11.020532+00:00 app[lapisshuga01.1]:   File "/app/plugins/imgur.py", line 125, in export_submission
    2016-12-28T16:52:11.020533+00:00 app[lapisshuga01.1]:     image = self.client.upload_from_url(import_url, config)
    2016-12-28T16:52:11.020534+00:00 app[lapisshuga01.1]:   File "/app/.heroku/python/lib/python3.5/site-packages/imgurpython/client.py", line 608, in upload_from_url
    2016-12-28T16:52:11.020534+00:00 app[lapisshuga01.1]:     return self.make_request('POST', 'upload', data, anon)
    2016-12-28T16:52:11.020535+00:00 app[lapisshuga01.1]:   File "/app/.heroku/python/lib/python3.5/site-packages/imgurpython/client.py", line 161, in make_request
    2016-12-28T16:52:11.020536+00:00 app[lapisshuga01.1]:     raise ImgurClientError(response_data['data']['error'], response.status_code)
    2016-12-28T16:52:11.020537+00:00 app[lapisshuga01.1]: imgurpython.helpers.error.ImgurClientError: (400) Image failed to upload.
    2016-12-28T16:52:11.020595+00:00 app[lapisshuga01.1]: 
    2016-12-28T16:52:11.021018+00:00 app[lapisshuga01.1]: INFO  - Successfully imported data from ImgurPlugin.export_submission()
    2016-12-28T16:52:11.378135+00:00 app[lapisshuga01.1]: INFO  - Replied comment to https://www.reddit.com/r/heyitsshugatest/comments/5kr6jh/another_issue_40_thing/

This part (towards the end) is the one that's worth reading:

    2016-12-28T16:52:11.020522+00:00 app[lapisshuga01.1]: ERROR - Broken exception catch Traceback (most recent call last):
    2016-12-28T16:52:11.020532+00:00 app[lapisshuga01.1]:   File "/app/plugins/imgur.py", line 125, in export_submission
    2016-12-28T16:52:11.020533+00:00 app[lapisshuga01.1]:     image = self.client.upload_from_url(import_url, config)
    2016-12-28T16:52:11.020534+00:00 app[lapisshuga01.1]:   File "/app/.heroku/python/lib/python3.5/site-packages/imgurpython/client.py", line 608, in upload_from_url
    2016-12-28T16:52:11.020534+00:00 app[lapisshuga01.1]:     return self.make_request('POST', 'upload', data, anon)
    2016-12-28T16:52:11.020535+00:00 app[lapisshuga01.1]:   File "/app/.heroku/python/lib/python3.5/site-packages/imgurpython/client.py", line 161, in make_request
    2016-12-28T16:52:11.020536+00:00 app[lapisshuga01.1]:     raise ImgurClientError(response_data['data']['error'], response.status_code)
    2016-12-28T16:52:11.020537+00:00 app[lapisshuga01.1]: imgurpython.helpers.error.ImgurClientError: (400) Image failed to upload.

**Comment by spiral6** [comment]
This is not the bot's fault, it's something on Imgur's end. I've tried manually uploading the image and it doesn't work, it just sends me an error as well saying unable to upload.
